#include "images.h"

const ext_img_desc_t images[24] = {
    { "icon_location", &img_icon_location },
    { "icon_temp", &img_icon_temp },
    { "icon_arrow_up", &img_icon_arrow_up },
    { "icon_arrow_down", &img_icon_arrow_down },
    { "icon_umid", &img_icon_umid },
    { "icon_wind", &img_icon_wind },
    { "icon_pressure", &img_icon_pressure },
    { "icon_eye", &img_icon_eye },
    { "icon_sereno", &img_icon_sereno },
    { "icon_sereno_notte", &img_icon_sereno_notte },
    { "icon_parzialmente_nuvoloso", &img_icon_parzialmente_nuvoloso },
    { "icon_parzialmente_nuvoloso_notte", &img_icon_parzialmente_nuvoloso_notte },
    { "icon_coperto", &img_icon_coperto },
    { "icon_nebbia", &img_icon_nebbia },
    { "icon_nebbia_notte", &img_icon_nebbia_notte },
    { "icon_pioviggine", &img_icon_pioviggine },
    { "icon_pioviggine_congelante", &img_icon_pioviggine_congelante },
    { "icon_pioggia", &img_icon_pioggia },
    { "icon_pioggia_congelante", &img_icon_pioggia_congelante },
    { "icon_neve", &img_icon_neve },
    { "icon_granelli_neve", &img_icon_granelli_neve },
    { "icon_temporale", &img_icon_temporale },
    { "icon_temporale_grandine", &img_icon_temporale_grandine },
    { "icon_sconosciuto", &img_icon_sconosciuto },
};
